ui: tape
browsers:
  - name: chrome
    version: latest
    os: 'Mac 10.11'
  - name: internet explorer
    version: 9..11
    os: 'Windows 10'
  - name: firefox
    version: latest
    os: 'Mac 10.11'
  - name: microsoftedge
    version: latest
  - name: safari
    version: latest
    os: 'Mac 10.11'
  - name: iphone
    version: '8.4..9.2'
  - name: android
    version: '4.3..5.1'
  - name: opera
    version: latest
    platform: 'Windows 10'
browserify:
  - transform:
      name: es2020
      global: true
  - transform: sheetify/transform
